# Generated by Django 5.1 on 2024-09-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.TextField()),
                ('type_number', models.TextField()),
            ],
            options={
                'db_table': 'admin_types',
            },
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('type', models.IntegerField()),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('avatar', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=2)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='Catalog_pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('added_at', models.DateTimeField()),
                ('catalog_id', models.IntegerField()),
            ],
            options={
                'db_table': 'catalog_pages',
            },
        ),
        migrations.CreateModel(
            name='Catalogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.TextField()),
                ('end_date', models.TextField()),
                ('image_link', models.TextField()),
                ('pages', models.IntegerField()),
                ('active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'catalogs',
            },
        ),
    ]
